insert into public.menu_item (other_name, category, description, hot, image_url, ingredients, name, price)
values (null, 'Juice', 'Freshly squeezed orange juice, pure vitamin C delight', false,
        'https://ik.imagekit.io/byte/orange.jpg', 'orange', 'Sunshine in a Glass', 3),
       (null, 'Juice', 'A thirst-quenching mix of fresh lemons and sugar', false,
        'https://ik.imagekit.io/byte/lemonade.jpg', 'lemon, sugar, water', 'Classic Lemonade', 2.5),
       (null, 'Juice', '100% apple juice, a taste of crisp autumn mornings', false,
        'https://ik.imagekit.io/byte/applejuice.jpg', 'apple', 'The Crunchy Apple', 2.5),
       (null, 'Juice', 'A refreshing blend of kiwi and banana', false,
        'https://ik.imagekit.io/byte/kiwijuice.jpg', 'kiwi, banana', 'Kiwi Banana Blast', 3.5),
       (null, 'Juice', 'Pink grapefruit juice, a burst of tangy goodness', false,
        'https://ik.imagekit.io/byte/grapefruitjuice.jpg', 'grapefruit', 'The Ruby Refresher', 3),
       (null, 'Juice', 'A vibrant mix of papaya, mango, and orange juice', false,
        'https://ik.imagekit.io/byte/cocktail.jpg', 'papaya, mango, orange', 'Tropical Escape',
        3.5),
       (null, 'Juice', 'A healthy blend of spinach, apple, and ginger', false,
        'https://ik.imagekit.io/byte/appleblend.jpg', 'spinach, apple, ginger', 'The Green Glow',
        4),
       (null, 'Coffee', 'A bold espresso shot to jumpstart your day', true,
        'https://ik.imagekit.io/byte/espresso.jpg', 'espresso', 'The Kickstart', 1.5),
       (null, 'Coffee', 'Cold brew for a slow sip, smooth finish', false,
        'https://ik.imagekit.io/byte/coldbrew.jpg', 'coffee grounds, cold water', 'The Night Owl',
        3),
       (null, 'Coffee', 'Dreamy blend of espresso, steamed milk, and milk foam', true,
        'https://ik.imagekit.io/byte/cappuccino.jpg', 'espresso, steamed milk, milk foam',
        'The Cloud Whisperer', 2.5),
       (null, 'Coffee', 'Mocha magic - latte with a delightful chocolate twist', true,
        'https://ik.imagekit.io/byte/mocha.jpg', 'espresso, steamed milk, chocolate flavoring',
        'The Chocolaty Fix', 3),
       (null, 'Pancakes', 'Classic pancakes topped with fresh berries and whipped cream', true,
        'https://ik.imagekit.io/byte/berrypancake.jpg', 'pancakes, fresh berries, whipped cream',
        'Berry Burst', 6),
       (null, 'Pancakes',
        'Buttermilk pancakes studded with chocolate chips, served with chocolate sauce', true,
        'https://ik.imagekit.io/byte/chocolatepancake.jpg',
        'pancakes, chocolate chips, chocolate sauce', 'Chocolate Chip Delight', 6.5),
       (null, 'Cake', 'Light and fluffy lemon cake with fresh blueberries and lemon glaze',
        false, 'https://ik.imagekit.io/byte/lemoncake.jpg',
        'flour, sugar, eggs, fat (butter or oil), lemon (zest and juice), liquids (milk or buttermilk), leavening (baking powder), blueberries, lemon glaze',
        'Lemon Blueberry Delight', 4),
       (null, 'Cake', 'Rich chocolate cake with chocolate ganache frosting', false,
        'https://ik.imagekit.io/byte/chocolatecake.jpg',
        'flour, cocoa powder, sugar, eggs, fat (butter or oil), milk, chocolate (chips or melted)',
        'Chocolate Decadence', 4.5),
       (null, 'Cake', 'Moist carrot cake with cream cheese frosting and walnuts', false,
        'https://ik.imagekit.io/byte/carrotcake.jpg',
        'flour, sugar, eggs, oil, carrots, spices (cinnamon, nutmeg), cream cheese frosting, walnuts (optional)',
        'Classic Carrot Cake', 4),
       (null, 'Omelette', 'A classic omelette filled with your choice of vegetables', true,
        'https://ik.imagekit.io/byte/omelette.jpg', 'eggs, vegetables, cheese (optional)',
        'Vegetable Omelette', 6),
       (null, 'Sweets', 'Freshly baked blueberry muffin', false,
        'https://ik.imagekit.io/byte/muffin.jpg', 'blueberry, eggs, baking powder',
        'Blueberry Muffin', 2.5),
       (null, 'Sweets',
        'A light and fluffy donut covered in rich chocolate frosting and colorful sprinkles', false,
        'https://ik.imagekit.io/byte/chocolate-donut-sprinkles.jpg',
        'flour, sugar, eggs, milk, chocolate frosting, sprinkles',
        'Chocolate Frosted Donut with Sprinkles', 1.5),
       (null, 'Sweets', 'Flaky croissant filled with rich chocolate', false,
        'https://ik.imagekit.io/byte/croissant.jpg', 'dough, chocolate, egg wash (optional)',
        'Chocolate Croissant', 2.5),
       (null, 'Sweets', 'Warm, gooey cinnamon roll with a sweet glaze', true,
        'https://ik.imagekit.io/byte/cinnamonroll.jpg',
        'dough, cinnamon sugar filling, cream cheese frosting (optional)', 'Cinnamon Roll', 3.5),
       (null, 'Sweets',
        'A classic French pastry with layers of puff pastry and rich pastry cream', false,
        'https://ik.imagekit.io/byte/millefeuilles.jpg', 'puff pastry dough, pastry cream, glaze',
        'Millefeuille', 2),
       (null, 'Sandwich',
        'A customizable breakfast wrap filled with scrambled eggs, your choice of cheese, and other delicious options.',
        true, 'https://ik.imagekit.io/byte/burrito.jpg',
        'tortilla, scrambled eggs, black beans, bell peppers, onions, spinach, tomatoes, sour cream, guacamole',
        'Breakfast Burrito', 5.99),
       (null, 'Sandwich',
        'Freshly smashed avocado on toasted bread, drizzled with olive oil and seasoned with salt and pepper. Can be customized with additional toppings.',
        false, 'https://ik.imagekit.io/byte/avocado-toast.jpg',
        'avocado, toasted bread, olive oil, salt, pepper, poached egg', 'Avocado Toast', 4.25);
